{{- if .Values.auth_key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsidp.fullname" . }}-authkey
  namespace: {{ .Release.Namespace }}
stringData:
  auth_key: {{ .Values.auth_key }}
{{- end -}}